name: Test Build

on: [push, pull_reques]

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest]
    runs-on: ${{matrix-platform}}
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Run CMake
      run: mkdir out && mkdir out/debug &&  cmake --preset linux-debug
    - name: Build CLI
      run: cmake --build --preset linux-debug --target astro_cli
