name: Test Build

on: [push, pull_request]

jobs:
  
  test-build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Prepare System
      run: sudo apt-get install -y libxmu-dev libxi-dev libgl-dev
    - uses: Jimver/cuda-toolkit@v0.2.8
      id: cuda-toolkit
      with:
        cuda: '11.7.0'
    - name: Run CMake
      run: mkdir out && mkdir out/debug &&  cmake --preset linux-debug
    - name: Build CLI
      run: cmake --build --preset linux-debug --target astro_cli
 
  test-build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - uses: Jimver/cuda-toolkit@v0.2.8
      id: cuda-toolkit
      with:
        cuda: '11.7.0'
    - name: Run CMake
      run: mkdir out && mkdir out/debug &&  cmake --preset windows-debug
    - name: Build CLI
      run: cmake --build --preset windows-debug --target astro_cli
